version: "3"

services:

  coordinator:
    build:
      context: .
      dockerfile: coordinator/coordinator.dockerfile
    image: dev/styx-coordinator:latest
    ports:
      - "8886:8888"
    env_file:
      - env/minio.env
    environment:
      - KAFKA_URL=kafka1:19092
      - HEARTBEAT_LIMIT=300000
      - HEARTBEAT_CHECK_INTERVAL=50000

  worker:
    build:
      context: .
      dockerfile: worker/worker.dockerfile
    image: dev/styx:latest
    environment:
      - WORKER_THREADS=4
      - INGRESS_TYPE=KAFKA
      - KAFKA_URL=kafka1:19092
      - DISCOVERY_HOST=coordinator
      - DISCOVERY_PORT=8888
    env_file:
      - env/minio.env
    deploy:
      resources:
        limits:
          cpus: '4'
        reservations:
          cpus: '4'
