version: "3.7"

x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-01-18T22-51-28Z
  command: server --console-address ":9001" http://minio1/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    - MINIO_ROOT_USER=minio
    - MINIO_ROOT_PASSWORD=minio123
  healthcheck:
    # Health check command as per https://github.com/minio/minio/issues/18389
    test: ["CMD", "mc", "ready", "local"]
    interval: 30s
    timeout: 20s
    retries: 3

services:

# starts 1 docker container running a minio server instance.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  nginx:
    image: nginx:1.25.3-alpine
    hostname: nginx
    volumes:
    # Local lighter nginx conf on par with minio's conf for dev cluster
      - ./minio_nginx_dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1

## This config uses default local driver.
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
